import './globals.css';
import { Karla } from 'next/font/google';
import Navbar from './components/Navbar';

// NEXTAUTH: GETTING SESSION INFORMATION ⭐️
// Here we use `getServerSession` to get the session information from the server
// and pass it down to a Navbar component. Function `next-auth/next` allows you
// to fetch the session information directly from the server/route api.
import { getServerSession } from 'next-auth/next';
import { authOptions } from '@/pages/api/auth/[...nextauth]';

import { ReactNode } from 'react';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const karla = Karla({
  subsets: ['latin-ext'],
});

interface Props {
  children: ReactNode;
}

export default async function RootLayout({ children }: Props) {
  const session = await getServerSession(authOptions);
  // console.log('RootLayout > getServerSession: ', session);
  return (
    <html lang="en">
      <body className={`${karla.className} mx-4 lg:mx-64`}>
        <Navbar user={session?.user} expires={session?.expires as string} />
        {children}
      </body>
    </html>
  );
}
